apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName.app }}-dpl
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName.app }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.appName.app }}-app
    spec:
      containers:
      {{- with .Values.container }}
      - name: {{ .name }}
        image: {{ .image }}
        env: 
        {{- range .env }}
          - name: {{ .name }} 
            value: {{ .value }}
        {{- end }}
        volumeMounts: 
          {{- toYaml .volumeMounts | nindent 9 }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .port }}
      {{- end }}
    volumes: 
      {{- toYaml  .Values.container.volumes | nindent 6}}