apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-app-data
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
  #volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
